from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class UiSmokeTest(unittest.TestCase):
    def test_react_app_mentions_llm_required_and_dynamic_runtime(self) -> None:
        source = (ROOT / "ui" / "src" / "App.tsx").read_text()
        self.assertIn('reasoning_verified: "Reasoning"', source)
        self.assertIn('text2sql_verified: "Text-to-SQL"', source)
        self.assertIn('longcontext_verified: "Long Context"', source)
        self.assertIn('personalization_verified: "Personalization"', source)
        self.assertIn('safety_verified: "Safety"', source)
        self.assertIn("llm-required", source)
        self.assertIn("EvoSkill Foundry 😎", source)
        self.assertIn("Start verified run", source)
        self.assertIn("run failure", source)
        self.assertIn("<h2>Runtime Profile</h2>", source)
        self.assertIn("<h2>Launch Controls</h2>", source)
        self.assertIn("<h2>Active Run Stream</h2>", source)
        self.assertIn("<h2>Latest Cached Report</h2>", source)
        self.assertIn("No cached report for this task yet", source)
        self.assertIn('aria-label="Theme"', source)
        self.assertIn("selection rules", source)
        self.assertIn("Item-level outcomes", source)
        self.assertIn("Episode-level outcomes", source)
        self.assertIn("items scheduled", source)
        self.assertIn("episodes scheduled", source)
        self.assertIn("Generation {item.latestGeneration || 0}/{task.generationBudget || \"?\"}", source)
        self.assertIn("Response", source)
        self.assertIn("Question.", source)
        self.assertIn("Instruction.", source)
        self.assertIn("Target", source)
        self.assertIn("Current Search State", source)
        self.assertIn("round ${summary.generation} avg ${formatObjectiveValueFromUnit(summary.averageObjective, task.objectiveUnit)}", source)
        self.assertIn("Episode trace", source)
        self.assertIn("Latest Candidate", source)
        self.assertIn("Winner", source)
        self.assertIn("actual_display", source)
        self.assertIn("fail -> pass", source)
        self.assertIn("Run memory log", source)
        self.assertIn("will be used for eval.", source)
        self.assertIn("Demo warning: running more than 50 coding items here is not recommended.", source)
        self.assertIn("Single-item task: cap disabled", source)
        self.assertIn("Blank uses the current default.", source)
        self.assertIn("Category", source)
        self.assertIn("Browse Mode", source)
        self.assertIn("Turn Mode", source)
        self.assertIn('const DEFAULT_BROWSE_MODE = "general_intelligence";', source)
        self.assertIn('const SAFETY_BROWSER_MODE = "safety";', source)
        self.assertIn('return "General Intelligence";', source)
        self.assertIn('return "Single Turn";', source)
        self.assertIn('return "Safety";', source)
        self.assertIn('return "Multi Turn";', source)
        self.assertIn("task.supports_max_items || task.supports_max_episodes || task.interaction_mode === \"multi_turn\"", source)
        self.assertIn("Task Browser", source)
        self.assertIn("Tracked Benchmarks", source)
        self.assertIn('new URLSearchParams(window.location.search).get("debug")', source)
        self.assertIn("const showTrackedBenchmarks = useMemo(() => debugModeEnabled(), []);", source)
        self.assertIn("const visibleTasks = useMemo(() => strictVisibleTasks, [strictVisibleTasks]);", source)
        self.assertIn("No tasks in this slice", source)
        self.assertIn("No runnable local tasks match", source)
        self.assertIn("Parallel Eval", source)
        self.assertIn("LLM Concurrency", source)
        self.assertIn("groupTasksByBrowseMode", source)
        self.assertIn("groupTasksByCategory", source)
        self.assertIn("personalizationCategoryLabel", source)
        self.assertIn("personaBenchmarkCategoryLabel", source)
        self.assertIn("personalizationSecondaryCategoryLabel", source)
        self.assertIn("safetyCategoryLabel", source)
        self.assertIn("safetyFocusLabel", source)
        self.assertIn("safetyBenchmarkCategoryLabel", source)
        self.assertIn("subjectDomainLabel", source)
        self.assertIn("officialMetricBackendLabel", source)
        self.assertIn("metricFidelityLabel", source)
        self.assertIn("referenceStatusLabel", source)
        self.assertIn("referenceImplementationStatusLabel", source)
        self.assertIn("referenceImplementationStatusTone", source)
        self.assertIn("taskShapeLabel", source)
        self.assertIn("scoringModeLabel", source)
        self.assertIn("running</span>", source)
        self.assertIn("planned</span>", source)
        self.assertIn("blocked</span>", source)
        self.assertIn('return "Character Knowledge";', source)
        self.assertIn('return "Character Portrayal";', source)
        self.assertIn('return "Consistency / Robustness";', source)
        self.assertIn('return "User Personalization";', source)
        self.assertIn('return "Agentic Personalization";', source)
        self.assertIn('jailbreak_attack: "Jailbreak / Attack"', source)
        self.assertIn('should_refuse: "Should Refuse"', source)
        self.assertIn('over_refusal: "Over-refusal"', source)
        self.assertIn('factuality_hallucination: "Factuality / Hallucination"', source)
        self.assertIn('policy_drift: "Policy Drift"', source)
        self.assertIn('benign_utility: "Benign Utility"', source)
        self.assertIn('safety_degradation: "Safety Degradation"', source)
        self.assertIn("Eval Model", source)
        self.assertIn("policy model", source)
        self.assertIn("eval model", source)
        self.assertIn("Official metric:", source)
        self.assertIn("Protocol:", source)
        self.assertIn("reference.protocol_summary", source)
        self.assertIn("reference.official_dimensions", source)
        self.assertIn("eval model required", source)
        self.assertIn('"agent-benchmark": "Agent"', source)
        self.assertIn('coding: "Code"', source)
        self.assertIn('qa: "QA"', source)
        self.assertIn("Frontier Parents", source)
        self.assertIn("Max Evolve Rounds", source)
        self.assertIn("Proposal Calls per Branch", source)
        self.assertIn('const evalLimitLabel = "Eval Limit"', source)
        self.assertIn("Max Turns per Episode", source)
        self.assertIn("Use Skill", source)
        self.assertIn("showUseSkillField", source)
        self.assertIn('className="field field-row-start"', source)
        self.assertIn("Record Skill from This Run", source)
        self.assertIn('className="toggle-card"', source)
        self.assertIn("safety category", source)
        self.assertIn("TASK SELECTION", source)
        self.assertIn("TASK CONFIGURATION", source)
        self.assertIn("SKILL RECORD/LOAD", source)
        self.assertIn("all completed item memories from this eval prefix", source)
        self.assertIn("independent proposal requests per branch", source)
        self.assertIn('metric("endpoint", runtimeInfo.base_url)', source)
        self.assertNotIn("Runs execute one task at a time.", source)
        self.assertNotIn("Suite Config", source)
        self.assertNotIn("Benchmark Task", source)
        self.assertNotIn("configured via suite config", source)
        self.assertNotIn("LLM Queue", source)
        self.assertNotIn("Run main benchmark sequence", source)
        self.assertNotIn("Main benchmark comparison", source)
        self.assertNotIn("Branching evolution, task by task.", source)
        self.assertNotIn("EvoAlgo: Benchmark Workbench", source)
        self.assertNotIn("Autoresearch Benchmark Console", source)
        self.assertNotIn("Run verified search on benchmark tasks.", source)
        self.assertNotIn("Mainline Benchmarks", source)
        self.assertNotIn("mainline benchmark", source)
        self.assertNotIn("comparison slate", source)
        self.assertNotIn("sidecar", source)
        self.assertNotIn("Cached run reports", source)
        self.assertNotIn("Benchmark Reports", source)
        self.assertNotIn("Runtime and verifier configuration", source)
        self.assertNotIn('planning_verified: "Planning"', source)
        self.assertNotIn('deepsearch_verified: "Deep Search"', source)
        self.assertNotIn('terminal_verified: "Terminal"', source)
        self.assertNotIn("Agent Benchmarks", source)
        self.assertNotIn("Multihop Reasoning", source)
        self.assertNotIn("Smoke / Regression", source)
        self.assertNotIn("Smoke / Regression Reports", source)
        self.assertNotIn("Generation Cap", source)
        self.assertNotIn("Candidates / Branch", source)
        self.assertNotIn("Candidates Count per Branch", source)
        self.assertNotIn("items opened", source)
        self.assertNotIn("Item IDs (Optional)", source)
        self.assertNotIn('<span className="badge">{runtimeInfo.mode}</span>', source)
        self.assertNotIn('<span className="badge">runtime {runtimeInfo.active_model}</span>', source)
        self.assertNotIn("Auto Research Console", source)
        self.assertNotIn("Auto Research Foundry", source)
        self.assertNotIn("Benchmark LOL 😂", source)
        self.assertNotIn("Self/Co-Evolve Skill Lab 😎", source)
        self.assertNotIn("Demo warning: running more than 50 LiveCodeBench items here is not recommended.", source)
        self.assertNotIn('safety_verified: "Overrefusal"', source)
        self.assertNotIn("Live execution trace", source)
        self.assertNotIn('<p className="eyebrow">run launcher</p>', source)
        self.assertNotIn('<p className="eyebrow">runtime profile</p>', source)
        self.assertNotIn('<p className="eyebrow">live execution</p>', source)
        self.assertNotIn('<p className="eyebrow">selected task report</p>', source)
        self.assertNotIn('className="caption">launch controls</p>', source)
        self.assertNotIn('className="caption">active configuration</p>', source)
        self.assertNotIn('className="caption">active run stream</p>', source)
        self.assertNotIn('className="caption">selected task report</p>', source)

    def test_index_loads_react_entry(self) -> None:
        source = (ROOT / "ui" / "index.html").read_text()
        self.assertIn("EvoSkill Foundry 😎", source)
        self.assertNotIn("Auto Research Foundry", source)
        self.assertNotIn("Benchmark LOL 😂", source)
        self.assertNotIn("Self/Co-Evolve Skill Lab 😎", source)
        self.assertNotIn("Autoresearch Benchmark Console", source)
        self.assertNotIn("EvoAlgo: Benchmark Workbench", source)
        self.assertIn("/src/main.tsx", source)

    def test_styles_and_polling_guards_prevent_layout_blowout(self) -> None:
        app_source = (ROOT / "ui" / "src" / "App.tsx").read_text()
        styles = (ROOT / "ui" / "src" / "styles.css").read_text()
        self.assertIn('document.addEventListener("visibilitychange"', app_source)
        self.assertIn("IDLE_LATEST_RUN_POLL_MS", app_source)
        self.assertIn("LIVE_JOB_BACKGROUND_POLL_MS", app_source)
        self.assertIn("text-size-adjust: 100%", styles)
        self.assertIn("scrollbar-gutter: stable;", styles)
        self.assertIn("min-width: 0;", styles)
        self.assertIn("width: 100%;", styles)


if __name__ == "__main__":
    unittest.main()
