from __future__ import annotations

from app.configs.paths import ROOT


REQUIRED_ENV_KEYS = (
    "AUTORESEARCH_API_KEY",
    "AUTORESEARCH_API_BASE",
)
AVAILABLE_MODELS_ENV_KEY = "AUTORESEARCH_AVAILABLE_MODELS"
PRIMARY_MODEL_ENV_KEY = "AUTORESEARCH_PRIMARY_MODEL"
LLM_CONCURRENCY_ENV_KEY = "AUTORESEARCH_LLM_CONCURRENCY"
DEFAULT_PRIMARY_MODEL = "deepseek-chat"
DEFAULT_AVAILABLE_MODELS = ("deepseek-chat", "kimi-k2.5", "glm-5")
DEFAULT_RUNTIME_TEMPERATURE = 0.2
DEFAULT_RUNTIME_MAX_TOKENS = 4096
DEFAULT_RUNTIME_TIMEOUT_S = 45
DEFAULT_LLM_CONCURRENCY = 20

__all__ = [
    "AVAILABLE_MODELS_ENV_KEY",
    "DEFAULT_AVAILABLE_MODELS",
    "DEFAULT_LLM_CONCURRENCY",
    "DEFAULT_PRIMARY_MODEL",
    "DEFAULT_RUNTIME_MAX_TOKENS",
    "DEFAULT_RUNTIME_TEMPERATURE",
    "DEFAULT_RUNTIME_TIMEOUT_S",
    "LLM_CONCURRENCY_ENV_KEY",
    "PRIMARY_MODEL_ENV_KEY",
    "REQUIRED_ENV_KEYS",
    "ROOT",
]
